project:
  type: website
  output-dir: docs

website:
  title: "ADS_fundamentals"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: manual.qmd
        text: Course manual
      - href: preparation.qmd
        text: Preparation
      - href: lectures.qmd
      - href: assignments.qmd
        text: Assignments
      - href: exam.qmd
        text: Exam

format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true

editor: visual

